[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "A BepInEx patcher to fix MonoMod.RuntimeDetour's DetourContext.Dispose not working."
websiteUrl = "https://github.com/Hamunii/DetourContext.Dispose_Fix"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./Packages"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/Hamunii.DetourContext.Dispose_Fix.dll"
target = "/patchers/"

[publish]
categories = ["tools"]
# Get the list of communities from https://thunderstore.io/api/experimental/community/
communities = [
    "lethal-company",
    "content-warning",
    "plasma",
    "gloomwood",
    "repo",
]
